### PR TITLE
Travis build mmgrok - some updates

### PR DESCRIPTION
**Pull request by portante**
Tried this out locally on my fedora box to see if I could get it working.  I found a small fix needed for `make distcheck` to work.

### CODE REVIEW

**Comment by rgerhards** [comment]
thx, unfortunately we still can't get it to build on travis. @portante do you think it is time to give up?

**Comment by portante** [comment]
@rgerhards, we are so close!

The above failures that I see are the queue-persist.sh test flakiness, and the cannot find grok under clang.  I'll create a .travis.yml file where I can debug the location of the grok .so to see if I can't find the right -L string to use.

**Comment by rgerhards** [comment]
@portante I would be more than happy if you can find a solution. I have tried very hard yesterday, I am simply out of ideas...

**Comment by portante** [comment]
@rgerhards debugging it now, will collapse patches when I find something.

**Comment by rgerhards** [comment]
@portante thx! I hope you have better success than I did. Looking forward to result.

**Comment by portante** [comment]
Okay, found out why, the `libgrok.so` is just a link to `libgrok.so.1`, but that does not exist anywhere in the environment.  See the latest build in this series, line 345.

**Comment by rgerhards** [comment]
Mmhhh... But it worked when I give the full path name for linking.
Remember, that was when make distcheck failed... Strange

Sent from phone, thus brief.
Am 09.12.2015 20:07 schrieb "Peter Portante" <notifications@github.com>:

**Comment by portante** [comment]
@rgerhards, I don't get it, but this last round should get a full and proper travis run, where mmgrok is run under clang. ... Should ... ;)

**Comment by portante** [comment]
Okay, well the clang with GROK passed, the clang with normal tests passed, but the gcc with tests failed due to `incltest.sh` failing.

**Comment by rgerhards** [comment]
Well, if we get the clang static analyzer going (but not the rest) I think
we could merge this and have some useful success. After all, we don't have
any real tests. Can you do such a commit?

Rainer

Sent from phone, thus brief.
Am 09.12.2015 20:53 schrieb "Peter Portante" <notifications@github.com>:

**Comment by portante** [comment]
@rgerhards, can we first merge this patch set layered on yours?

**Comment by rgerhards** [comment]
Yup, but needs to wait roughly 9 hours before I can do.

Sent from phone, thus brief.
Am 09.12.2015 22:07 schrieb "Peter Portante" <notifications@github.com>:

**Comment by portante** [comment]
@rgerhards, sounds good.  We'll pick this up Thursday AM.

**Comment by portante** [comment]
@rgerhards, double check me, but `mmgrok` upholds under the scan, and I have made some changes to fix a few other ones.  Let me know if this is what you are looking for.

**Comment by rgerhards** [comment]
looks great, I'll see that I can merge it in today. IMHO it looks like a packaging bug that the actual lib is not installed when the dependencies are there, but great it looks solved now,

**Pull request merged**
